# Generated by Django 4.1.7 on 2023-02-28 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_add_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="is_done",
            new_name="is_active",
        ),
    ]
